In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cu118


### Creating a range of tensors and tensors-like

In [2]:
one_to_ten = torch.arange(1,11)

In [3]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### START-END-STEP

In [4]:
step_by_step = torch.arange(start=1,end=11,step=2)

In [5]:
step_by_step

tensor([1, 3, 5, 7, 9])

In [6]:
step_by_step.shape

torch.Size([5])

### Creating tensors-like

In [7]:
##* Shape bilgisi yoksa unput olarak like fonksiyonunu kullanabiliriz
ten_zeros = torch.zeros_like(input=step_by_step)

In [8]:
ten_zeros

tensor([0, 0, 0, 0, 0])

In [9]:
step_by_step

tensor([1, 3, 5, 7, 9])

### Int data types

In [11]:
int_32_tensor = torch.tensor([3,2,1],dtype=torch.int32)
int_32_tensor

tensor([3, 2, 1], dtype=torch.int32)

In [12]:
float_32_tensor = torch.tensor([32,2,1],dtype=torch.float32)

In [13]:
res = int_32_tensor*float_32_tensor

In [14]:
res

tensor([96.,  4.,  1.])

In [15]:
res.dtype

torch.float32

### Getting information from tensors

1. Tensors not right data type -> to get type we can use tensor.dtype 
2. Tensors not in right shape -> to get shape of device we can use tensor.shape
3. Tensors not in right device -> to get device of tensor we can use tensor.device

In [31]:
some_tensor = torch.rand(size=(3,4))
some_tensor

tensor([[0.0845, 0.8788, 0.0442, 0.6812],
        [0.6680, 0.0978, 0.3030, 0.9545],
        [0.7385, 0.3547, 0.7949, 0.1851]])

In [39]:
# Find out details about some tensor 
print(some_tensor.to('cpu'))
print(f'Data type of tensor: {some_tensor.dtype}')
print(f'Shape type of tensor: {some_tensor.shape}')
print(f'Device type of tensor: {some_tensor.device}')

tensor([[0.0845, 0.8788, 0.0442, 0.6812],
        [0.6680, 0.0978, 0.3030, 0.9545],
        [0.7385, 0.3547, 0.7949, 0.1851]])
Data type of tensor: torch.float32
Shape type of tensor: torch.Size([3, 4])
Device type of tensor: cpu
