In [2]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cu118


# Introduction to Tensors 

### Creating Tensors

### SCALAR

In [7]:

#*Scalar 
scalar = torch.tensor(7)
print(scalar)
print(scalar.type)

tensor(7)
<built-in method type of Tensor object at 0x0000023FD0B096C0>


In [8]:
scalar.ndim

0

In [12]:
# Get tensor back as python int 
scalar.item()

7

### VECTOR

In [21]:
# Vector 
vector = torch.tensor([[[7,7]],[[7,7]]])
print(vector)
print(vector.shape)
print(vector.ndim)

tensor([[[7, 7]],

        [[7, 7]]])
torch.Size([2, 1, 2])
3


### MATRIX

In [31]:
matrix = torch.tensor([[7,7,7],[7,7,7],[1,1,1]])
print(matrix)
print(f'dim: {matrix.ndim}')
print(f'shape: {matrix.shape}')

tensor([[7, 7, 7],
        [7, 7, 7],
        [1, 1, 1]])
dim: 2
shape: torch.Size([3, 3])


In [32]:
matrix[0][2]

tensor(7)

### TENSOR

In [37]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])


In [38]:
tensor.shape

torch.Size([1, 3, 3])

In [39]:
print(tensor)
print(f'dim: {tensor.ndim}')
print(f'shape: {tensor.shape}')

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
dim: 3
shape: torch.Size([1, 3, 3])


In [40]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [41]:
tensor[0][1]

tensor([4, 5, 6])

In [42]:
tensor[0][1][1]

tensor(5)