In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cu118


### Find Min, Max, Mean, Sum, etc(tensor aggregation)

In [4]:
x = torch.arange(0,100,10)

In [5]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
print(f'x min: {x.min()}')
print(f'x max: {x.max()}')

x min: 0
x max: 90


In [10]:
# find min-max through torch
print(f'torch.min(x): {torch.min(x)}')
print(f'torch.max(x): {torch.max(x)}')

torch.min(x): 0
torch.max(x): 90


In [11]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [12]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [14]:
x.type(torch.float32).mean()

tensor(45.)

In [15]:
# find the sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [29]:
y = torch.rand(10,2)

In [28]:
y

tensor([[0.1024, 0.8139, 0.1250, 0.2298, 0.6893, 0.6407, 0.3552, 0.3203, 0.8081,
         0.3491],
        [0.5801, 0.5275, 0.2633, 0.6054, 0.4822, 0.5075, 0.1807, 0.5763, 0.6851,
         0.5638]])

### Finding the Positional min and max

In [35]:
#* find the position value in tensor that has the minimum value with argmin
#* returns the tensor position where the min value is exists
x.argmin()

tensor(0)

In [37]:
x[0] = 104

In [39]:
x

tensor([104,  10,  20,  30,  40,  50,  60,  70,  80,  90])

In [38]:
x.argmin()

tensor(1)

In [41]:
# find the posistion of the max value in the tensor using argmax
x.argmax()

tensor(0)

In [42]:
torch.argmax(x)

tensor(0)

In [43]:
torch.argmin(x)

tensor(1)