In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cu118


## Selecting Devices to run code GPU or TENSORS

* GPU means faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything faster 



#* Getting the GPU 
1. Easiest - Use Google Colab for a free GPU
2. Use Your own GPU 
3. Use Cloud Computing - GCP, AWS, AZURE -> These services allows you to rent pc on the cloud

* For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this refer to PyThorch setup documentation

In [5]:
!nvidia-smi

Sat Jan 27 19:45:18 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.26                 Driver Version: 546.26       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8              10W /  95W |    150MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Check for GPU access by PyTorch

In [8]:
torch.cuda.is_available()

True

In [9]:

#* Setup device agnostic code 
device = 'cuda' if torch.cuda.is_available else 'cpu'

In [10]:
device

'cuda'

In [11]:
torch.cuda.device_count()

1

### Putting tensors and models into GPU 

* The reason is that we want our tensors/models on the GPU is because using a GPU results in faster computations
* Tensors as default inserted on the cpu 

In [24]:
tensor = torch.tensor(data=([1 ,2,3]),device='cpu')
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [25]:
tensor = tensor.to('cuda')

In [26]:
print(tensor,tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


### Moving tensors back to the cpu

In [27]:
tensor_on_cpu = tensor.to('cpu')

In [36]:
tensor_on_cpu+=1

In [33]:
tensor_on_cpu.numpy()

array([1, 2, 3], dtype=int64)

In [38]:
tensor_on_cpu, tensor

(tensor([2, 3, 4]), tensor([1, 2, 3], device='cuda:0'))