In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cu118


### PyThorch tensors and NumPy

- Numpy is a popular scientific python numerical computing library, because of this PyThorch has functionality to interact with it.

* Data in numpy wanted in tensor, so we need to convert numpy to tensor or maybe reverse also can be required

**torch.from_numpy(ndarray)**

**torch.Tensor.numpy()**

### NUMPY array to Tensor 

In [4]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

print(f'numpy : {array}')
print(f'tensor: {tensor}')


numpy : [1. 2. 3. 4. 5. 6. 7.]
tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [14]:
#* change the value of array, what will this do to 'tensor'
array = array+1

In [19]:
print(f'array (changed): {array} \ntensor: {tensor}')
print('Tensor did not changed')

array (changed): [2. 3. 4. 5. 6. 7. 8.] 
tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
Tensor did not changed


### Tensor to Numpy

In [5]:
array2 = torch.Tensor.numpy(tensor)

In [6]:
array2

array([1., 2., 3., 4., 5., 6., 7.])

In [7]:
print(f'numpy : {array}')
print(f'tensor: {tensor}')

numpy : [1. 2. 3. 4. 5. 6. 7.]
tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [23]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor2 = torch.Tensor.numpy(tensor)

In [24]:
tensor,numpy_tensor, numpy_tensor2

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [27]:
#change the value of Tensor and see if the numpy is changed

tensor = tensor +1

In [28]:
tensor,numpy_tensor, numpy_tensor2

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))