In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cu118


### Reproducibility (trying to take random out of the python)

* In short how a neural networks learns:
1. Start with random numbers 
2. Tensor operations 
3. Update random numbers to try to make them better representation of data 
4. again again again repeat above steps


To reduce randomness in reural networks and pythorch comes the ocncept of a random seed

Essentially what the random seed does is flavour the randomness

In [8]:
torch.rand(1,1)

tensor([[0.1317]])

In [9]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)


In [11]:
print(random_tensor_A)
print(random_tensor_B)
print(f'A==B = {random_tensor_A==random_tensor_B}')

tensor([[0.0324, 0.3620, 0.6208, 0.7880],
        [0.1403, 0.2561, 0.6877, 0.2660],
        [0.0787, 0.5063, 0.3924, 0.1060]])
tensor([[0.3251, 0.2198, 0.3029, 0.6198],
        [0.2697, 0.2981, 0.1533, 0.4963],
        [0.4700, 0.7205, 0.9251, 0.7423]])
A==B = tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [24]:
## Let's make some random but reproducable tensor
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)


In [25]:
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(f'C==D = {random_tensor_C==random_tensor_D}')


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
C==D = tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
