### Tensors with zeros and ones

In [3]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cu118


In [34]:
zeros = torch.ones(size=(3,4))
zeros = zeros+ torch.ones(size=zeros.shape)

In [35]:
zeros

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [36]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.3693, 0.9675, 0.6044, 0.0234],
        [0.4812, 0.6886, 0.8463, 0.3444],
        [0.6846, 0.7454, 0.3459, 0.3266]])

In [37]:
multiplication = zeros*random_tensor

In [38]:
multiplication

tensor([[0.7386, 1.9349, 1.2088, 0.0468],
        [0.9624, 1.3773, 1.6926, 0.6888],
        [1.3691, 1.4909, 0.6917, 0.6533]])

In [45]:
tensors_with_all_ones = torch.ones(size=(3,4))

In [46]:
tensors_with_all_ones.dtype

torch.float32