In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cu118


### Tensor Data Types

**NOTE:** Tensor data types is one of the 3 big errors you will run into in PyTorch & Deep Learning
1. Tensors not right data type 
2. Tensors not in right shape
3. Tensors not in right device

In [2]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)

In [3]:
float_32_tensor

tensor([3., 6., 9.])

In [4]:
float_32_tensor.dtype

torch.float32

In [12]:
float16_dtype= torch.tensor([3,3,2],dtype=torch.float64,device=None,requires_grad=False)

In [13]:
float16_dtype.device

device(type='cpu')

In [14]:
float_16_size = float_32_tensor.type(torch.half)

In [15]:
float_16_size

tensor([3., 6., 9.], dtype=torch.float16)

In [16]:
multiplication = float_16_size * float_32_tensor

In [17]:
multiplication

tensor([ 9., 36., 81.])

In [19]:
multiplication.dtype

torch.float32