In [4]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
print(torch.__version__)

2.1.2+cu118


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction 
* Multiplication (element-wise)
* Division
* Matrix Multiplication

### Addition - Subtraction

In [29]:
my_tensor = torch.tensor([1,2,3])
my_tensor

tensor([1, 2, 3])

In [103]:
my_tensor = my_tensor + 10
print(my_tensor)


tensor([10., 10., 10.])


In [40]:
my_tensor =  my_tensor-10
print(my_tensor)

tensor([0.1205, 0.2410, 0.3614])


### Multiplication and Division

In [41]:
my_tensor = torch.tensor([1,2,3])
my_tensor

tensor([1, 2, 3])

In [63]:
my_tensor= my_tensor*10
print(my_tensor)

tensor([-8446744073709551616,  1553255926290448384, -6893488147419103232])


In [110]:
my_tensor*torch.tensor([2,2])

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [105]:
my_tensor.dtype

torch.float32

In [104]:
my_tensor

tensor([10., 10., 10.])

In [106]:
my_tensor = my_tensor/8.3

In [108]:
my_tensor

tensor([1.2048, 1.2048, 1.2048])

In [107]:
my_tensor.dtype

torch.float32

# PyThorch In Build Functions for basic Operations

In [114]:
my_tensor.mul_(4)

tensor([4.8193, 4.8193, 4.8193])

In [115]:
my_tensor

tensor([4.8193, 4.8193, 4.8193])

In [120]:
my_tensor.div_(torch.tensor([1,2,2]))

tensor([4.8193, 2.4096, 2.4096])

In [121]:
my_tensor

tensor([4.8193, 2.4096, 2.4096])

### Matrix Multiplication

- Two main ways of matrix multiplication in neural networks and deep learning:

1. Element-wise multiplication 
2. Matrix multiplication (dot product)

- There are 2 main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match
    * (3,2) @ (2,3) -> This will work 
    * (2,3) @ (3,2) -> This will also work

2. The resulting matrix has the shape of the **outer dimensions**

### Element Wise

In [151]:
my_matrix = torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
my_matrix

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

In [152]:
print(f'Element Wise multiplication of my_matris*my_matris:\n {my_matrix*my_matrix}')

Element Wise multiplication of my_matris*my_matris:
 tensor([[ 1,  4,  9, 16],
        [ 1,  4,  9, 16],
        [ 1,  4,  9, 16]])


In [153]:
my_matrix2 = torch.tensor([2,2,2,2])
print(f'Element Wise multiplication of my_matris*my_matris:\n {my_matrix2*my_matrix}')

Element Wise multiplication of my_matris*my_matris:
 tensor([[2, 4, 6, 8],
        [2, 4, 6, 8],
        [2, 4, 6, 8]])


### Matrix Multiplication

In [181]:
my_matrix3 = torch.tensor([2,2,2,2])



In [182]:
%%time
print(f'Matrix multiplication of my_matris*my_matris:\n {torch.matmul(my_matrix,my_matrix3)}')

Matrix multiplication of my_matris*my_matris:
 tensor([20, 20, 20])
CPU times: total: 0 ns
Wall time: 0 ns


In [183]:
%%time
print(f'Matrix multiplication of my_matris*my_matris:\n {(my_matrix@my_matrix3)}')

Matrix multiplication of my_matris*my_matris:
 tensor([20, 20, 20])
CPU times: total: 0 ns
Wall time: 96.8 µs


In [188]:
torch.rand(size=(10,100))

tensor([[2.5595e-03, 4.7798e-01, 1.3597e-01, 5.6996e-01, 1.9012e-01, 4.1230e-01,
         8.6397e-01, 6.5388e-01, 9.4629e-01, 9.1107e-01, 1.7843e-01, 7.3691e-01,
         3.4453e-01, 4.4846e-01, 7.6120e-01, 8.1665e-01, 4.4127e-01, 8.8027e-01,
         7.4929e-01, 3.9152e-01, 6.5561e-01, 4.1813e-01, 7.1430e-01, 5.0994e-01,
         5.8877e-02, 3.0868e-01, 3.3858e-01, 8.3696e-01, 1.8103e-01, 4.1320e-01,
         9.1544e-01, 3.1769e-01, 8.5079e-01, 3.4101e-01, 1.7904e-01, 9.5577e-01,
         1.1342e-01, 3.7661e-01, 3.7590e-01, 7.5780e-01, 9.4195e-01, 2.6444e-01,
         4.0563e-01, 3.9204e-01, 1.0056e-02, 5.5370e-01, 1.0780e-01, 7.8804e-02,
         4.8733e-01, 4.7721e-02, 6.3191e-01, 5.5488e-01, 7.0018e-01, 2.6130e-01,
         8.2360e-01, 8.3643e-01, 9.1655e-02, 1.7610e-01, 4.2128e-01, 5.1772e-01,
         2.7036e-01, 4.5681e-01, 2.1080e-01, 8.4236e-01, 9.3917e-02, 8.5203e-01,
         7.9222e-01, 9.0821e-01, 1.7571e-02, 6.2414e-01, 4.7250e-01, 7.3152e-01,
         6.7569e-01, 9.9173e

In [195]:
%%time
print(f'Matrix multiplication of my_matris*my_matris:\n {(torch.rand(size=(10000,10000))@torch.rand(size=(10000,1000))).shape}')

Matrix multiplication of my_matris*my_matris:
 torch.Size([10000, 1000])
CPU times: total: 7.97 s
Wall time: 1.9 s


In [199]:
# Shapes for matrix multiplications 
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

In [206]:
torch.mm(tensor_A.T,tensor_B)


tensor([[ 76, 103],
        [100, 136]])

In [208]:
print(tensor_A.T.shape)
print(tensor_A.shape)

torch.Size([2, 3])
torch.Size([3, 2])


In [202]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

- To fix our tensor shape issue, we can manipulate the shape of one of our tensors using a **transpose**

A **Transpose** switches the axes or dimensions of a given tensor.